name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      env:
        MOEDAS_PATH: ${{ github.workspace }}/Input/moedas.xlsx
        LOG_DIR: ${{ github.workspace }}/Logs
        RESULTADO_PATH: ${{ github.workspace }}/resultado_cotacoes.xlsx
      run: |
        echo "MOEDAS_PATH=$MOEDAS_PATH"
        echo "LOG_DIR=$LOG_DIR"
        echo "RESULTADO_PATH=$RESULTADO_PATH"
    
    - name: Run script
      run: python cotacao_moedas.py

    - name: Commit arquivo gerado
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add resultado_cotacoes.xlsx
        git commit -m "CD: resultado_cotacoes.xlsx gerado automaticamente"
        git push
